<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(_TestTargetFrameworks)</TargetFrameworks>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="NetEvolve.Extensions.TUnit" />
    <PackageReference Include="TngTech.ArchUnitNET.TUnit" />
    <PackageReference Include="TUnit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\NetEvolve.HealthPublishers.ApplicationInsights\NetEvolve.HealthPublishers.ApplicationInsights.csproj" />
    <ProjectReference Include="..\..\src\NetEvolve.HealthPublishers.AWS.CloudWatch\NetEvolve.HealthPublishers.AWS.CloudWatch.csproj" />
    <ProjectReference Include="..\..\src\NetEvolve.HealthPublishers.Datadog\NetEvolve.HealthPublishers.Datadog.csproj" />
    <ProjectReference Include="..\..\src\NetEvolve.HealthPublishers.Elasticsearch\NetEvolve.HealthPublishers.Elasticsearch.csproj" />
    <ProjectReference Include="..\..\src\NetEvolve.HealthPublishers.OpenTelemetry\NetEvolve.HealthPublishers.OpenTelemetry.csproj" />
    <ProjectReference Include="..\..\src\NetEvolve.HealthPublishers.Opsgenie\NetEvolve.HealthPublishers.Opsgenie.csproj" />
    <ProjectReference Include="..\..\src\NetEvolve.HealthPublishers.PagerDuty\NetEvolve.HealthPublishers.PagerDuty.csproj" />
    <ProjectReference Include="..\..\src\NetEvolve.HealthPublishers.Prometheus.Metrics\NetEvolve.HealthPublishers.Prometheus.Metrics.csproj" />
    <ProjectReference Include="..\..\src\NetEvolve.HealthPublishers.Prometheus.PushGateway\NetEvolve.HealthPublishers.Prometheus.PushGateway.csproj" />
    <ProjectReference Include="..\..\src\NetEvolve.HealthPublishers.Seq\NetEvolve.HealthPublishers.Seq.csproj" />
    <ProjectReference Include="..\..\src\NetEvolve.HealthPublishers.Splunk\NetEvolve.HealthPublishers.Splunk.csproj" />
    <ProjectReference Include="..\..\src\NetEvolve.HealthPublishers.Webhook\NetEvolve.HealthPublishers.Webhook.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="NetEvolve.Extensions.TUnit.ArchitectureTestAttribute" />
  </ItemGroup>
</Project>
