<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(_TestTargetFrameworks)</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <NeutralLanguage>en</NeutralLanguage>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.CloudWatch" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="NetEvolve.Extensions.TUnit" />
    <PackageReference Include="OpenTelemetry.Exporter.InMemory" />
    <PackageReference Include="Testcontainers" />
    <PackageReference Include="Testcontainers.Elasticsearch" />
    <PackageReference Include="Testcontainers.Floci" />
    <PackageReference Include="Testcontainers.Seq" />
    <PackageReference Include="TUnit" />
    <PackageReference Include="Verify.TUnit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\NetEvolve.HealthPublishers.Abstractions\NetEvolve.HealthPublishers.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\NetEvolve.HealthPublishers.ApplicationInsights\NetEvolve.HealthPublishers.ApplicationInsights.csproj" />
    <ProjectReference Include="..\..\src\NetEvolve.HealthPublishers.AWS.CloudWatch\NetEvolve.HealthPublishers.AWS.CloudWatch.csproj" />
    <ProjectReference Include="..\..\src\NetEvolve.HealthPublishers.Datadog\NetEvolve.HealthPublishers.Datadog.csproj" />
    <ProjectReference Include="..\..\src\NetEvolve.HealthPublishers.Elasticsearch\NetEvolve.HealthPublishers.Elasticsearch.csproj" />
    <ProjectReference Include="..\..\src\NetEvolve.HealthPublishers.OpenTelemetry\NetEvolve.HealthPublishers.OpenTelemetry.csproj" />
    <ProjectReference Include="..\..\src\NetEvolve.HealthPublishers.Prometheus.Metrics\NetEvolve.HealthPublishers.Prometheus.Metrics.csproj" />
    <ProjectReference Include="..\..\src\NetEvolve.HealthPublishers.Prometheus.PushGateway\NetEvolve.HealthPublishers.Prometheus.PushGateway.csproj" />
    <ProjectReference Include="..\..\src\NetEvolve.HealthPublishers.Seq\NetEvolve.HealthPublishers.Seq.csproj" />
    <ProjectReference Include="..\..\src\NetEvolve.HealthPublishers.Splunk\NetEvolve.HealthPublishers.Splunk.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="NetEvolve.Extensions.TUnit.IntegrationTestAttribute" />
  </ItemGroup>
</Project>
