<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(_ProjectTargetFrameworks)</TargetFrameworks>
    <Description>Contains an IHealthCheckPublisher implementation that pushes health report results as JSON to a user-configured webhook endpoint.</Description>
    <PackageTags>$(PackageTags);webhook</PackageTags>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>
</Project>
